
spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: rgo-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-dev.com:5122/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: rgo-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-test.com:5122/eureka/